# Site settings
description: CSE Software Portal
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cse-software.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Duong Do
user_description: Student at Saint John's University
user_title: Student Researcher
email: dhdo@csbsju.com
twitter_username: lorem_ipsum
github_username:  duongdo27
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Getting involved
    url: /getting-involved
  - title: Annotated Bibliography
    url: /annotated-bibliography
  - title: Tags
    url: /tags
  - title: How to contribute
    url: /how-to-contribute
  - title: About Us
    url: /about-us

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
